# This workflow will install build Sphinx documentation and make it ready for Gihub Pages

name: Luminaire Sphinx Docs

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - feature/*

jobs:
  build-and-delpoy:

    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx rst2pdf sphinx-rtd-theme rinohtype

    - name: Build Sphinx docs
      run: |
        pwd
        ls
        cd docs_source
        make html

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html/
